---
- hosts: all
  gather_facts: yes
  tasks:
  - name: "Populate service facts"
    service_facts:
  - name: "See the service <ntpd> facts as they are"
    debug:
      msg: "{{ansible_facts.services['ntpd.service'].state}}"
  - name: "Verify if ntpd is running!"
    assert:
      that:
        - "'{{ansible_facts.services['ntpd.service'].state}}' == 'running'"
      fail_msg: "ntpf is down, costs money every minute!"
      success_msg: "Good to go, money is comming our way"
