---
- name: configure firewalld
  hosts: all
  become: true

  tasks:
  - name: permit port 6789 tcp port
    firewalld:
      zone: public
      port: 6789/tcp
      permanent: yes
      state: enabled

  - name: permit port 6800-7100 tcp port
    firewalld:
      zone: public
      port: 6800-7100/tcp
      permanent: yes
      state: enabled

  - name: reload firewalld Service
    service:
      name: firewalld
      state: restarted

