---
- name: Yum update
  hosts: ceph-node2
  become: true

  tasks:
  - name: update yum
    yum:
      name: "*"
      state: latest
    when: ansible_facts['os_family'] == 'RedHat' and ansible_facts ['distribution_major_version'] >= '7'
